export const ROUTES = {
  LOGIN: "/login",
  FORGET_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",  
  DASHBOARD: "/dashboard",
  CONTENT_LIBRARY: "/content-library",
  UPLOAD: "/upload",
  UPLOAD_WITH_ID: "/upload/:id",
  MY_TOPICS: "/my-topics",
  REVIEW_QUEUE: "/review-queue",
  USERS: "/users",
  SETTINGS: "/settings",
  USER_PROFILE: "/profile",
  NOCIFICATIONS: "/notifications",
  MEDICAL_TOPICS : "/medical-topics",
};