export const ROUTES = {
  LOGIN: "/login",
  FORGET_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",  
  DASHBOARD: "/dashboard",
  UPLOAD: "/upload",
  UPLOAD_WITH_ID: "/upload/:id",
  MY_TOPICS: "/my-topics",
  REVIEW_QUEUE: "/review-queue",
  USERS: "/users",
  SETTINGS: "/settings",
  USER_PROFILE: "/profile",
  NOCIFICATIONS: "/notifications",
  MEDICAL_TOPICS : "/medical-topics",
  MY_DOCTOR_NOTES : "/doctor-notes",
  AGENCY_POC : "/agency-poc",
  SCRIPT : "/script",
  VIDEOS : "/videos",
  CONTENT_APPROVER_SCRIPTS : "/content-approver-script",
  CONTENT_APPROVER_VIDEOS : "/content-approver-videos",
  PUBLISHER : "/publisher",
};