import { ROUTES } from "../routes/RouterConstant";


export const ROLE_ACCESS = {
  SUPER_ADMIN: [
    ROUTES.DASHBOARD,
    ROUTES.USERS,
    ROUTES.NOCIFICATIONS
  ],

  MEDICAL_AFFAIRS: [
    // ROUTES.DASHBOARD,
    ROUTES.MEDICAL_TOPICS,
    // ROUTES.UPLOAD,
    ROUTES.REVIEW_QUEUE,
    ROUTES.NOCIFICATIONS
  ],

  DOCTOR: [
    // ROUTES.DASHBOARD,
    ROUTES.MY_TOPICS,
    ROUTES.UPLOAD,
    ROUTES.MY_DOCTOR_NOTES,
    ROUTES.REVIEW_QUEUE,
    ROUTES.NOCIFICATIONS
  ],

  BRAND_REVIEWER: [
    // ROUTES.DASHBOARD,
    ROUTES.REVIEW_QUEUE,
    ROUTES.NOCIFICATIONS
  ],

  AGENCY_POC: [
    // ROUTES.DASHBOARD,
    ROUTES.UPLOAD,
    ROUTES.NOCIFICATIONS
  ],

  CONTENT_APPROVER: [
    // ROUTES.DASHBOARD,
    ROUTES.REVIEW_QUEUE,
    ROUTES.NOCIFICATIONS
  ],

  PUBLISHER: [
    // ROUTES.DASHBOARD,
    ROUTES.REVIEW_QUEUE,
    ROUTES.NOCIFICATIONS
  ],
};