import { ROUTES } from "../routes/RouterConstant";

export const ROLE_ACCESS = {
  SUPER_ADMIN: [
    ROUTES.DASHBOARD,
    ROUTES.USERS,
    ROUTES.NOCIFICATIONS,
    ROUTES.MEDICAL_TOPICS,
    ROUTES.REVIEW_QUEUE,
    ROUTES.MY_TOPICS,
    ROUTES.MY_DOCTOR_NOTES,
    ROUTES.UPLOAD,
    ROUTES.AGENCY_POC,
    ROUTES.SCRIPT,
    ROUTES.VIDEOS,
    ROUTES.CONTENT_APPROVER_SCRIPTS,
    ROUTES.CONTENT_APPROVER_VIDEOS,
  ],

  MEDICAL_AFFAIRS: [
    // ROUTES.DASHBOARD,
    ROUTES.MEDICAL_TOPICS,
    // ROUTES.UPLOAD,
    // ROUTES.REVIEW_QUEUE,
    ROUTES.CONTENT_APPROVER_SCRIPTS,
    ROUTES.CONTENT_APPROVER_VIDEOS,
    ROUTES.NOCIFICATIONS,
  ],

  DOCTOR: [
    // ROUTES.DASHBOARD,
    ROUTES.MY_TOPICS,
    ROUTES.UPLOAD,
    ROUTES.MY_DOCTOR_NOTES,
    // ROUTES.REVIEW_QUEUE,
    ROUTES.CONTENT_APPROVER_SCRIPTS,
    ROUTES.CONTENT_APPROVER_VIDEOS,
    ROUTES.NOCIFICATIONS,
  ],

  BRAND_REVIEWER: [
    // ROUTES.DASHBOARD,
    ROUTES.CONTENT_APPROVER_SCRIPTS,
    ROUTES.CONTENT_APPROVER_VIDEOS,
    // ROUTES.REVIEW_QUEUE,
    ROUTES.NOCIFICATIONS,
  ],

  AGENCY_POC: [
    // ROUTES.DASHBOARD,
    ROUTES.AGENCY_POC,
    ROUTES.SCRIPT,
    ROUTES.VIDEOS,
    // ROUTES.UPLOAD,
    ROUTES.NOCIFICATIONS,
  ],

  CONTENT_APPROVER: [
    // ROUTES.DASHBOARD,
    ROUTES.CONTENT_APPROVER_SCRIPTS_NEW,
    ROUTES.CONTENT_APPROVER_VIDEOS,
    // ROUTES.REVIEW_QUEUE,
    ROUTES.NOCIFICATIONS,
  ],

  PUBLISHER: [
    // ROUTES.DASHBOARD,
    ROUTES.PUBLISHER,
    ROUTES.NOCIFICATIONS,
  ],
};
